[package]
name = "kitchen"
edition = "2021"
version = "0.1.0"

[dependencies]
feed-rs = "2.3.1"
rusqlite = "0.33.0"
reqwest.version = "0.12.12"
reqwest.features = ["json"]
tokio.version = "1.43.0"
tokio.features = ["full"]


