[package]
name = "kitchen"
edition = "2021"
version = "0.1.0"

[dependencies]
feed-rs = { version = "2.3.1" }
reqwest = { version = "0.12.12", features = ["json"] }
rusqlite = { version = "0.33.0" }
tokio = { version = "1.43.0", features = ["full"] }
                 
        
