[package]
name = "caterer-web"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1" }
feed-rs = { version = "2.3.1" }
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.43", features = ["full"] }
                        
